class CreateMatchPlayersTable < ActiveRecord::Migration
  def up
    create_table :match_players do |t|
      t.integer :match_id
      t.integer :account_id
      t.integer :clan_id
      t.integer :hero_id
      t.integer :position
      t.integer :team
      t.integer :level
      t.integer :wins
      t.integer :losses
      t.integer :concedes
      t.integer :concedevotes
      t.integer :buybacks
      t.integer :discos
      t.integer :kicked
      t.float :pub_skill
      t.integer :pub_count
      t.float :amm_solo_rating
      t.integer :amm_solo_count
      t.float :amm_team_rating
      t.integer :amm_team_count
      t.float :avg_score
      t.integer :herokills
      t.integer :herodmg
      t.integer :heroexp
      t.integer :herokillsgold
      t.integer :heroassists
      t.integer :deaths
      t.integer :goldlost2death
      t.integer :secs_dead
      t.integer :teamcreepkills
      t.integer :teamcreepdmg
      t.integer :teamcreepexp
      t.integer :teamcreepgold
      t.integer :neutralcreepkills
      t.integer :neutralcreepdmg
      t.integer :neutralcreepexp
      t.integer :neutralcreepgold
      t.integer :bdmg
      t.integer :bdmgexp
      t.integer :razed
      t.integer :bgold
      t.integer :denies
      t.integer :exp_denied
      t.integer :gold
      t.integer :gold_spent
      t.integer :exp
      t.integer :actions
      t.integer :secs
      t.integer :consumables
      t.integer :wards
      t.integer :time_earning_exp
      t.integer :bloodlust
      t.integer :doublekill
      t.integer :triplekill
      t.integer :quadkill
      t.integer :annihilation
      t.integer :ks3
      t.integer :ks4
      t.integer :ks5
      t.integer :ks6
      t.integer :ks7
      t.integer :ks8
      t.integer :ks9
      t.integer :ks10
      t.integer :ks15
      t.integer :smackdown
      t.integer :humiliation
      t.integer :nemesis
      t.integer :retribution
      t.integer :used_token
      t.text :tag
      t.text :nickname
      t.text :cli_name
    end
  end

  def down
    drop_table :match_players
  end
end
